apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
  namespace: demo-app
data:
  application.yml: |
    spring:
      datasource:
        url: jdbc:postgresql://${DB_HOST:postgres-service}:${DB_PORT:5432}/${DB_NAME:sample}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
      liquibase:
        change-log: classpath:/db/changelog/db.changelog-master.yaml
        default-schema: public
        contexts: production
      jpa:
        hibernate:
          ddl-auto: none
        show-sql: false
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    logging:
      level:
        liquibase: info
        org.springframework: info
        root: info
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          show-details: always
      metrics:
        export:
          prometheus:
            enabled: true
